### ISSUE TITLE
Export to clipboard

### ISSUE THREAD

**Issue by sergey-lapin** [lapanoid/redux-import-export-monitor#1]
@calesce I guess I can make project boilerplate and make simple export to clipboard "helloworld" button to begin this.

**Comment by calesce** [comment]
Hey, I went ahead and did this because it was an easy first step :smile: For now I'm just using a fork of Redux DevTools, since we'll need to add an action creator to [devTools.js](https://github.com/lapanoid/redux-import-export-monitor/blob/master/src/devTools.js) to somehow call `recomputeStates` with the imported state/actions.

Let me know if you can think of a more elegant solution than just exposing `recomputeStates` to the monitor. :smile_cat: 

EDIT:
I managed to hack together a quick input area to test out the import stuff in an hour or so. It works pretty well! It didn't seem to consistently re-compute state, but it's also late here and I'm fairly tired and delirious, so I might be wrong :smile:

**Comment by sergey-lapin** [comment]
@calesce Awesome work! You did not give me any chances to do anything actually=) I will check this out and test.

**Comment by sergey-lapin** [comment]
Works without any problems, great work again!
I will reduce this today to keep it minimal.

**Comment by sergey-lapin** [comment]
I made a [PR](https://github.com/gaearon/redux-devtools/pull/49) to add recompute states functionality to devtools.js

**Comment by calesce** [comment]
Good stuff, thanks!
